### ISSUE TITLE
Use kebab-case for timestamp comparison parameters (`smaller-column`, `greater-column`)

### ISSUE THREAD

**Issue by flitzpiepe93** [sparkdq-community/sparkdq#25]
# Use kebab-case for timestamp comparison parameters (`smaller-column`, `greater-column`)

Currently, column-based comparison checks like `column-less-than-check` require the following configuration syntax:

```yaml
- check: column-less-than-check
  check-id: chronological
  smaller_column: tpep_pickup_datetime
  greater_column: tpep_dropoff_datetime
  inclusive: false
```

This works fine functionally, but the parameter naming is inconsistent with other check configurations. For example:

- `min_value` → `min-value`
- `check_id` → `check-id`
- `start_column` → `start-column`

For better consistency and YAML aesthetics, it would be more intuitive to use **kebab-case** for `smaller_column` and `greater_column` as well:

```yaml
- check: column-less-than-check
  check-id: chronological
  smaller-column: tpep_pickup_datetime
  greater-column: tpep_dropoff_datetime
  inclusive: false
```

This aligns with the naming convention used across the rest of the framework and simplifies cognitive load for users writing declarative configurations.

## 🔧 Suggested Change

Update the `BaseColumnComparisonCheckConfig` to alias the existing snake_case parameters with kebab-case equivalents using Pydantic's `Field(..., alias="...")` syntax. Also ensure that validation works identically for both programmatic and declarative use.

## ✅ Benefits

- Consistent YAML structure
- Improved readability and predictability
- Better support for config-as-code workflows

Let me know if this change aligns with the intended design of the config system. I'm happy to open a PR if helpful.
